import React, {Component} from 'react';
import './FooterMobile.scss';

import {Accordion,AccordionTab} from 'primereact/accordion';

export default class FooterMobile extends Component {
        
    render() {
        return (
            <div>
                <div className="content-section implementation">
                    <h3>Footer for mobile version</h3>
                    <Accordion>
                        <AccordionTab header="Je commence mon abonnement au n°1 :">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur neque purus, malesuada in dictum ut, sodales vel lacus. In hac habitasse platea dictumst. Donec consectetur pharetra nibh quis mattis. Praesent lacinia velit sed ex ullamcorper viverra. Vestibulum sagittis eros ut risus viverra consectetur. Morbi elementum leo sapien, in tempor turpis tempus eu. Integer suscipit lobortis diam, nec rutrum urna malesuada sed. Morbi nec imperdiet massa. Duis ante risus, condimentum a eros nec, placerat iaculis ligula. Sed id tortor ut lacus finibus feugiat nec sit amet sapien. Curabitur laoreet mauris sed quam porttitor, et rhoncus tellus cursus. Donec et condimentum odio.</p>
                            <p>Fusce pharetra non turpis ut pretium. Sed sagittis tempor lacinia. Proin diam elit, semper vel sollicitudin sit amet, porttitor eget mi. Vivamus porta dapibus enim ut rutrum. Donec pretium rhoncus ipsum. Integer at est tempus lacus mollis commodo. Vivamus vel malesuada purus. Aenean placerat, libero ut scelerisque varius, magna neque dapibus libero, at vehicula mi massa ac ipsum.</p>
                            <p>Praesent nec erat consectetur, aliquet est a, convallis nunc. Sed eget lectus ultricies, dictum nibh a, ullamcorper tortor. Nullam non mollis libero. Etiam a est ut ipsum tristique pellentesque quis ut leo. Maecenas varius ac purus id tristique. Nulla dictum nisl sit amet ullamcorper euismod. Curabitur molestie diam eu leo cursus varius. Cras placerat vulputate scelerisque. Vivamus tristique nisl mauris, ut hendrerit justo ultrices ut. Etiam quis aliquet justo. Nunc a massa libero. Nullam bibendum venenatis urna ac imperdiet. Phasellus in nunc vel risus dapibus luctus. Praesent nec rutrum tortor. Duis tincidunt, mi sit amet cursus pellentesque, turpis ligula tristique enim, eget fermentum ex odio sit amet enim. Nulla vel suscipit magna, eu auctor diam.</p>
                            <p>Aenean quis dapibus orci, quis convallis dolor. Praesent ut arcu eget tellus elementum vehicula id id tortor. Duis lacinia mi quis suscipit auctor. Aenean lectus leo, finibus id iaculis quis, condimentum non velit. Curabitur ullamcorper dui nulla, non sollicitudin ex interdum eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse ullamcorper aliquam diam, sit amet aliquam sapien tincidunt sagittis.</p>
                            <p>Duis tincidunt diam in ex lobortis finibus. Nulla tortor magna, blandit in volutpat laoreet, porttitor at nunc. Vestibulum id vestibulum sem. Praesent consectetur mauris sit amet tortor vehicula, in placerat est malesuada. Etiam eget vehicula felis. Nunc elit nisi, faucibus at congue vitae, pellentesque sit amet tortor. Nunc mollis magna libero, in efficitur lorem rhoncus nec. Ut porta eget enim sit amet venenatis.</p>
                        </AccordionTab>
                        <AccordionTab header="Je commence mon abonnement au n°2 :">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur neque purus, malesuada in dictum ut, sodales vel lacus. In hac habitasse platea dictumst. Donec consectetur pharetra nibh quis mattis. Praesent lacinia velit sed ex ullamcorper viverra. Vestibulum sagittis eros ut risus viverra consectetur. Morbi elementum leo sapien, in tempor turpis tempus eu. Integer suscipit lobortis diam, nec rutrum urna malesuada sed. Morbi nec imperdiet massa. Duis ante risus, condimentum a eros nec, placerat iaculis ligula. Sed id tortor ut lacus finibus feugiat nec sit amet sapien. Curabitur laoreet mauris sed quam porttitor, et rhoncus tellus cursus. Donec et condimentum odio.</p>
                            <p>Fusce pharetra non turpis ut pretium. Sed sagittis tempor lacinia. Proin diam elit, semper vel sollicitudin sit amet, porttitor eget mi. Vivamus porta dapibus enim ut rutrum. Donec pretium rhoncus ipsum. Integer at est tempus lacus mollis commodo. Vivamus vel malesuada purus. Aenean placerat, libero ut scelerisque varius, magna neque dapibus libero, at vehicula mi massa ac ipsum.</p>
                            <p>Praesent nec erat consectetur, aliquet est a, convallis nunc. Sed eget lectus ultricies, dictum nibh a, ullamcorper tortor. Nullam non mollis libero. Etiam a est ut ipsum tristique pellentesque quis ut leo. Maecenas varius ac purus id tristique. Nulla dictum nisl sit amet ullamcorper euismod. Curabitur molestie diam eu leo cursus varius. Cras placerat vulputate scelerisque. Vivamus tristique nisl mauris, ut hendrerit justo ultrices ut. Etiam quis aliquet justo. Nunc a massa libero. Nullam bibendum venenatis urna ac imperdiet. Phasellus in nunc vel risus dapibus luctus. Praesent nec rutrum tortor. Duis tincidunt, mi sit amet cursus pellentesque, turpis ligula tristique enim, eget fermentum ex odio sit amet enim. Nulla vel suscipit magna, eu auctor diam.</p>
                            <p>Aenean quis dapibus orci, quis convallis dolor. Praesent ut arcu eget tellus elementum vehicula id id tortor. Duis lacinia mi quis suscipit auctor. Aenean lectus leo, finibus id iaculis quis, condimentum non velit. Curabitur ullamcorper dui nulla, non sollicitudin ex interdum eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse ullamcorper aliquam diam, sit amet aliquam sapien tincidunt sagittis.</p>
                            <p>Duis tincidunt diam in ex lobortis finibus. Nulla tortor magna, blandit in volutpat laoreet, porttitor at nunc. Vestibulum id vestibulum sem. Praesent consectetur mauris sit amet tortor vehicula, in placerat est malesuada. Etiam eget vehicula felis. Nunc elit nisi, faucibus at congue vitae, pellentesque sit amet tortor. Nunc mollis magna libero, in efficitur lorem rhoncus nec. Ut porta eget enim sit amet venenatis.</p>
                        </AccordionTab>
                        <AccordionTab header="Je commence mon abonnement au n°3 :">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur neque purus, malesuada in dictum ut, sodales vel lacus. In hac habitasse platea dictumst. Donec consectetur pharetra nibh quis mattis. Praesent lacinia velit sed ex ullamcorper viverra. Vestibulum sagittis eros ut risus viverra consectetur. Morbi elementum leo sapien, in tempor turpis tempus eu. Integer suscipit lobortis diam, nec rutrum urna malesuada sed. Morbi nec imperdiet massa. Duis ante risus, condimentum a eros nec, placerat iaculis ligula. Sed id tortor ut lacus finibus feugiat nec sit amet sapien. Curabitur laoreet mauris sed quam porttitor, et rhoncus tellus cursus. Donec et condimentum odio.</p>
                            <p>Fusce pharetra non turpis ut pretium. Sed sagittis tempor lacinia. Proin diam elit, semper vel sollicitudin sit amet, porttitor eget mi. Vivamus porta dapibus enim ut rutrum. Donec pretium rhoncus ipsum. Integer at est tempus lacus mollis commodo. Vivamus vel malesuada purus. Aenean placerat, libero ut scelerisque varius, magna neque dapibus libero, at vehicula mi massa ac ipsum.</p>
                            <p>Praesent nec erat consectetur, aliquet est a, convallis nunc. Sed eget lectus ultricies, dictum nibh a, ullamcorper tortor. Nullam non mollis libero. Etiam a est ut ipsum tristique pellentesque quis ut leo. Maecenas varius ac purus id tristique. Nulla dictum nisl sit amet ullamcorper euismod. Curabitur molestie diam eu leo cursus varius. Cras placerat vulputate scelerisque. Vivamus tristique nisl mauris, ut hendrerit justo ultrices ut. Etiam quis aliquet justo. Nunc a massa libero. Nullam bibendum venenatis urna ac imperdiet. Phasellus in nunc vel risus dapibus luctus. Praesent nec rutrum tortor. Duis tincidunt, mi sit amet cursus pellentesque, turpis ligula tristique enim, eget fermentum ex odio sit amet enim. Nulla vel suscipit magna, eu auctor diam.</p>
                            <p>Aenean quis dapibus orci, quis convallis dolor. Praesent ut arcu eget tellus elementum vehicula id id tortor. Duis lacinia mi quis suscipit auctor. Aenean lectus leo, finibus id iaculis quis, condimentum non velit. Curabitur ullamcorper dui nulla, non sollicitudin ex interdum eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse ullamcorper aliquam diam, sit amet aliquam sapien tincidunt sagittis.</p>
                            <p>Duis tincidunt diam in ex lobortis finibus. Nulla tortor magna, blandit in volutpat laoreet, porttitor at nunc. Vestibulum id vestibulum sem. Praesent consectetur mauris sit amet tortor vehicula, in placerat est malesuada. Etiam eget vehicula felis. Nunc elit nisi, faucibus at congue vitae, pellentesque sit amet tortor. Nunc mollis magna libero, in efficitur lorem rhoncus nec. Ut porta eget enim sit amet venenatis.</p>
                        </AccordionTab>
                        <AccordionTab header="Je commence mon abonnement au n°4 :">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur neque purus, malesuada in dictum ut, sodales vel lacus. In hac habitasse platea dictumst. Donec consectetur pharetra nibh quis mattis. Praesent lacinia velit sed ex ullamcorper viverra. Vestibulum sagittis eros ut risus viverra consectetur. Morbi elementum leo sapien, in tempor turpis tempus eu. Integer suscipit lobortis diam, nec rutrum urna malesuada sed. Morbi nec imperdiet massa. Duis ante risus, condimentum a eros nec, placerat iaculis ligula. Sed id tortor ut lacus finibus feugiat nec sit amet sapien. Curabitur laoreet mauris sed quam porttitor, et rhoncus tellus cursus. Donec et condimentum odio.</p>
                            <p>Fusce pharetra non turpis ut pretium. Sed sagittis tempor lacinia. Proin diam elit, semper vel sollicitudin sit amet, porttitor eget mi. Vivamus porta dapibus enim ut rutrum. Donec pretium rhoncus ipsum. Integer at est tempus lacus mollis commodo. Vivamus vel malesuada purus. Aenean placerat, libero ut scelerisque varius, magna neque dapibus libero, at vehicula mi massa ac ipsum.</p>
                            <p>Praesent nec erat consectetur, aliquet est a, convallis nunc. Sed eget lectus ultricies, dictum nibh a, ullamcorper tortor. Nullam non mollis libero. Etiam a est ut ipsum tristique pellentesque quis ut leo. Maecenas varius ac purus id tristique. Nulla dictum nisl sit amet ullamcorper euismod. Curabitur molestie diam eu leo cursus varius. Cras placerat vulputate scelerisque. Vivamus tristique nisl mauris, ut hendrerit justo ultrices ut. Etiam quis aliquet justo. Nunc a massa libero. Nullam bibendum venenatis urna ac imperdiet. Phasellus in nunc vel risus dapibus luctus. Praesent nec rutrum tortor. Duis tincidunt, mi sit amet cursus pellentesque, turpis ligula tristique enim, eget fermentum ex odio sit amet enim. Nulla vel suscipit magna, eu auctor diam.</p>
                            <p>Aenean quis dapibus orci, quis convallis dolor. Praesent ut arcu eget tellus elementum vehicula id id tortor. Duis lacinia mi quis suscipit auctor. Aenean lectus leo, finibus id iaculis quis, condimentum non velit. Curabitur ullamcorper dui nulla, non sollicitudin ex interdum eget. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse ullamcorper aliquam diam, sit amet aliquam sapien tincidunt sagittis.</p>
                            <p>Duis tincidunt diam in ex lobortis finibus. Nulla tortor magna, blandit in volutpat laoreet, porttitor at nunc. Vestibulum id vestibulum sem. Praesent consectetur mauris sit amet tortor vehicula, in placerat est malesuada. Etiam eget vehicula felis. Nunc elit nisi, faucibus at congue vitae, pellentesque sit amet tortor. Nunc mollis magna libero, in efficitur lorem rhoncus nec. Ut porta eget enim sit amet venenatis.</p>
                        </AccordionTab>
                    </Accordion>
                </div>
            </div>
        )
    }
}
